# Generated by Django 5.2.8 on 2025-12-30 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Área de Interés',
                'verbose_name_plural': 'Áreas de Interés',
                'db_table': 'area_interes',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('duracion_semestres', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'db_table': 'carrera',
            },
        ),
        migrations.CreateModel(
            name='CatEstadoAlumno',
            fields=[
                ('id_estado_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado del Alumno',
                'db_table': 'cat_estado_alumno',
            },
        ),
        migrations.CreateModel(
            name='CatEstadoHistorial',
            fields=[
                ('id_estado_historial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado del Historial',
                'db_table': 'cat_estado_historial',
            },
        ),
        migrations.CreateModel(
            name='CatEstadoInscripcion',
            fields=[
                ('id_estado_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado de Inscripción',
                'db_table': 'cat_estado_inscripcion',
            },
        ),
        migrations.CreateModel(
            name='CatGravedadIncidente',
            fields=[
                ('id_gravedad_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Gravedad del Incidente',
                'db_table': 'cat_gravedad_incidente',
            },
        ),
        migrations.CreateModel(
            name='CatTipoCarrera',
            fields=[
                ('id_tipo_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Carrera',
                'db_table': 'cat_tipo_carrera',
            },
        ),
        migrations.CreateModel(
            name='CatTipoIncidente',
            fields=[
                ('id_tipo_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Incidente',
                'db_table': 'cat_tipo_incidente',
            },
        ),
        migrations.CreateModel(
            name='CatTipoRelacionTutor',
            fields=[
                ('id_tipo_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Relación Tutor',
                'db_table': 'cat_tipo_relacion_tutor',
            },
        ),
        migrations.CreateModel(
            name='CatTurno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Turno',
                'db_table': 'cat_turno',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Incidente',
                'db_table': 'incidente',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('creditos', models.IntegerField(default=7)),
                ('nivel_sugerido', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'db_table': 'nivel_educativo',
            },
        ),
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telefono_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.ImageField(blank=True, default='tutor_placeholder.png', null=True, upload_to='tutores/')),
            ],
            options={
                'verbose_name': 'Padre o Tutor',
                'verbose_name_plural': 'Padres o Tutores',
                'db_table': 'padre_tutor',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id_universidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'universidad',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('boleta', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('semestre_actual', models.IntegerField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('lugar_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, default='alumno_placeholder.png', null=True, upload_to='alumnos/')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto_emergencia_telefono2', models.CharField(blank=True, max_length=20, null=True)),
                ('carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.carrera')),
                ('estado_alumno', models.ForeignKey(blank=True, db_column='id_estado_alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.catestadoalumno')),
            ],
            options={
                'verbose_name': 'Alumno',
                'db_table': 'alumno',
            },
        ),
        migrations.CreateModel(
            name='AlumnoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('estado_inscripcion', models.ForeignKey(db_column='id_estado_inscripcion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.catestadoinscripcion')),
            ],
            options={
                'verbose_name': 'Inscripción Grupo',
                'verbose_name_plural': 'Inscripciones Grupos',
                'db_table': 'alumno_grupo',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.ForeignKey(blank=True, db_column='id_tipo_carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.cattipocarrera'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(blank=True, default='docente_placeholder.png', null=True, upload_to='docentes/')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_emergencia_parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('grado_academico', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion_procedencia', models.CharField(blank=True, max_length=150, null=True)),
                ('anios_experiencia', models.IntegerField(blank=True, null=True)),
                ('experiencia_laboral', models.TextField(blank=True, null=True)),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('areas_interes', models.ManyToManyField(blank=True, db_table='docente_area_interes', to='academico.areainteres')),
            ],
            options={
                'verbose_name': 'Docente',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('clave_grupo', models.CharField(max_length=50)),
                ('grado', models.IntegerField(blank=True, null=True)),
                ('periodo', models.CharField(max_length=20)),
                ('alumnos', models.ManyToManyField(through='academico.AlumnoGrupo', to='academico.alumno')),
                ('docente', models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
                ('turno', models.ForeignKey(blank=True, db_column='id_turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.catturno')),
            ],
            options={
                'verbose_name': 'Grupo',
                'db_table': 'grupo',
            },
        ),
        migrations.AddField(
            model_name='alumnogrupo',
            name='grupo',
            field=models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='academico.grupo'),
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.CASCADE, to='academico.alumno')),
                ('estado_historial', models.ForeignKey(blank=True, db_column='id_estado_historial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.catestadohistorial')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'db_table': 'historial_academico',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo', models.ForeignKey(db_column='id_grupo', on_delete=django.db.models.deletion.CASCADE, to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Horario',
                'db_table': 'horario',
            },
        ),
    ]
