# Generated by Django 5.2.8 on 2025-12-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoRelacionTutor',
            fields=[
                ('id_tipo_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Relación (Tutor)',
                'db_table': 'cat_tipo_relacion_tutor',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id_nivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'db_table': 'nivel_educativo',
            },
        ),
        migrations.CreateModel(
            name='PadreTutor',
            fields=[
                ('id_tutor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_relacion', models.ForeignKey(db_column='id_tipo_relacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.cattiporelaciontutor')),
            ],
            options={
                'verbose_name': 'Padre o Tutor',
                'verbose_name_plural': 'Padres y Tutores',
                'db_table': 'padre_tutor',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('boleta', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nivel', models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='academico.niveleducativo')),
                ('tutor', models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.padretutor')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumno',
            },
        ),
    ]
