# Generated by Django 5.2.8 on 2025-12-30 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='admin',
            field=models.ForeignKey(db_column='id_admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidente',
            name='alumno',
            field=models.ForeignKey(blank=True, db_column='id_alumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.alumno'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='docente',
            field=models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='gravedad',
            field=models.ForeignKey(blank=True, db_column='id_gravedad_incidente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.catgravedadincidente'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipo_incidente',
            field=models.ForeignKey(db_column='id_tipo_incidente', on_delete=django.db.models.deletion.CASCADE, to='academico.cattipoincidente'),
        ),
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.carrera'),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='materia',
            field=models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='academico.materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nivel_educativo',
            field=models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='academico.niveleducativo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='nivel',
            field=models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='academico.niveleducativo'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='nivel',
            field=models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='academico.niveleducativo'),
        ),
        migrations.AddField(
            model_name='padretutor',
            name='tipo_relacion',
            field=models.ForeignKey(db_column='id_tipo_relacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.cattiporelaciontutor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tutor',
            field=models.ForeignKey(blank=True, db_column='id_tutor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.padretutor'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='universidad',
            field=models.ForeignKey(blank=True, db_column='id_universidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.universidad'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnogrupo',
            unique_together={('alumno', 'grupo')},
        ),
    ]
