# Generated by Django 5.2.8 on 2025-12-07 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'verbose_name': 'Alumno'},
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente'},
        ),
        migrations.AlterModelOptions(
            name='padretutor',
            options={'verbose_name': 'Padre o Tutor'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.CharField(blank=True, default='/static/img/alumno_placeholder.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='foto',
            field=models.CharField(blank=True, default='/static/img/docente_placeholder.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='padretutor',
            name='foto',
            field=models.CharField(blank=True, default='/static/img/tutor_placeholder.png', max_length=255, null=True),
        ),
    ]
