# Generated by Django 5.2.8 on 2025-12-14 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='docente',
            field=models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.CASCADE, to='academico.docente'),
        ),
    ]
