# Generated by Django 5.2.8 on 2025-12-28 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_alter_grupo_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadDocente',
            fields=[
                ('id_disponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad docente',
                'db_table': 'disponibilidad_docente',
            },
        ),
        migrations.CreateModel(
            name='ReglaHorario',
            fields=[
                ('id_regla', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('tipo_alumno', models.CharField(blank=True, max_length=20, null=True)),
                ('duracion_bloque_min', models.IntegerField()),
                ('materias_max_por_dia', models.IntegerField()),
                ('descanso_duracion_min', models.IntegerField()),
                ('descanso_despues_bloque', models.IntegerField()),
                ('permitir_taller', models.BooleanField(default=False)),
                ('bloque_taller', models.IntegerField(blank=True, null=True)),
                ('carga_docente_max', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('nivel', models.ForeignKey(db_column='id_nivel', on_delete=django.db.models.deletion.CASCADE, to='academico.niveleducativo')),
            ],
            options={
                'verbose_name': 'Regla de horario',
                'db_table': 'regla_horario',
            },
        ),
        migrations.CreateModel(
            name='DocenteMateria',
            fields=[
                ('id_docente_materia', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.SmallIntegerField(default=1)),
                ('docente', models.ForeignKey(db_column='id_docente', on_delete=django.db.models.deletion.CASCADE, to='academico.docente')),
                ('materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.CASCADE, to='academico.materia')),
            ],
            options={
                'verbose_name': 'Docente por materia',
                'db_table': 'docente_materia',
                'unique_together': {('docente', 'materia')},
            },
        ),
    ]
