# Generated by Django 5.2.8 on 2025-12-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_disponibilidaddocente_reglahorario_docentemateria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidaddocente',
            options={'verbose_name': 'Disponibilidad docente', 'verbose_name_plural': 'Disponibilidades docentes'},
        ),
        migrations.AlterModelOptions(
            name='docentemateria',
            options={'verbose_name': 'Docente por materia', 'verbose_name_plural': 'Docentes por materia'},
        ),
        migrations.AlterModelOptions(
            name='reglahorario',
            options={'verbose_name': 'Regla de horario', 'verbose_name_plural': 'Reglas de horario'},
        ),
    ]
