# Generated by Django 5.2.8 on 2025-12-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_alter_disponibilidaddocente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='sesiones_por_semana',
            field=models.IntegerField(default=5),
        ),
    ]
