# Generated by Django 5.2.8 on 2026-01-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0006_materia_sesiones_por_semana"),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="capacidad_maxima",
            field=models.PositiveIntegerField(default=40),
        ),
    ]
