# Generated by Django 5.2.8 on 2026-01-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alumno_fecha_eliminacion'),
        ('academico', '0007_grupo_capacidad_maxima'),
    ]

    operations = [
    ]
